import type { NextPage } from 'next'
import {useState} from 'react';
import Head from 'next/head'
import {
  getBhkType,
  getCorporationWaterRatio,
  getBorewellWaterRatio,
  tankerWaterRate,
  getBhkRatioRate,
  getGuests,
  getAllWaterUse
} from "../service/service";
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [result, setResult] = useState('');
  const fileFormat: RegExp = /(ALLOT_WATER )(.*?)(BILL)/g

  const showFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    const reader = new FileReader();
    reader.onload = async (e) => {
      if (e.target) {
        const text = JSON.stringify(e.target.result);

        if (text && text.match(fileFormat)) {
          const bhkType = getBhkType(text);
          const corporationWaterRatio = getCorporationWaterRatio(text);
          const borewellWaterRatio = getBorewellWaterRatio(text);

          const allWater = getAllWaterUse(bhkType, getGuests(text));
          const allRate =
            getBhkRatioRate(
              bhkType,
              corporationWaterRatio,
              borewellWaterRatio
            ) + tankerWaterRate(getGuests(text));

          setResult(allWater + ":" + allRate);
          console.log(allWater + " " + allRate);
        } else {
          console.log("error file");
          alert("wrong file");
        }
      }
    };
    if (e.target.files) {
      reader.readAsText(e.target.files[0]);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{result !== "" ? result : `Water management`}</h1>

        <div className={styles.grid}>
          <input accept="text/plain" type="file" onChange={showFile} />
        </div>
      </main>
    </div>
  );
}

export default Home
